### ISSUE TITLE
ModuleNotFoundError: No module named 'models.arch_util'

### ISSUE THREAD

**Issue by erhathaway** [DPS2022/diffusion-posterior-sampling#1]
Hi, I am getting this error while trying to run the code with the `nonlinear deblur` task. If I try the `super resolution` task it works.

```shell
python3 sample_condition.py \                                              
--model_config=configs/model_config.yaml \
--diffusion_config=configs/diffusion_config.yaml \
--task_config=configs/nonlinear_deblur_config.yaml;
```

```
Device set to cpu.
Traceback (most recent call last):
  File "sample_condition.py", line 121, in <module>
    main()
  File "sample_condition.py", line 57, in main
    operator = get_operator(device=device, **measure_config['operator'])
  File "/home/ethan/diffusion-posterior-sampling/guided_diffusion/measurements.py", line 32, in get_operator
    return __OPERATOR__[name](**kwargs)
  File "/home/ethan/diffusion-posterior-sampling/guided_diffusion/measurements.py", line 178, in __init__
    self.blur_model = self.prepare_nonlinear_blur_model(opt_yml_path)     
  File "/home/ethan/diffusion-posterior-sampling/guided_diffusion/measurements.py", line 184, in prepare_nonlinear_blur_model
    from bkse.models.kernel_encoding.kernel_wizard import KernelWizard
  File "/home/ethan/diffusion-posterior-sampling/bkse/models/kernel_encoding/kernel_wizard.py", line 3, in <module>
    import models.arch_util as arch_util
ModuleNotFoundError: No module named 'models.arch_util'
```

**Comment by DPS2022** [comment]
Hello, did you clone two repositories in the readme? For non-linear deblur, we used an external repository to simulate. Please check it.

**Comment by Siddharth-Shrivastava7** [comment]
Hi @erhathaway, 
you need to make following changes to work non-linear deblur task work ( I am assuming that you cloned non linear deblur repository as **bkse** name and moved inside diffusion posterior sampling repo) : 

1. In _diffusion-posterior-sampling/bkse/models/kernel_encoding/kernel_wizard.py_  : 
- Change `import models.arch_util as arch_util` into  `import bkse.models.arch_util as arch_util` 
- Change `from models.backbones.resnet import ResidualBlock_noBN, ResnetBlock` into `from bkse.models.backbones.resnet import ResidualBlock_noBN, ResnetBlock` 
- Change `from models.backbones.unet_parts import UnetSkipConnectionBlock` into `from bkse.models.backbones.unet_parts import UnetSkipConnectionBlock` 

2. In _diffusion-posterior-sampling/bkse/models/backbones/resnet.py_  : 
- Change `from models.arch_util import initialize_weights` into `from bkse.models.arch_util import initialize_weights`  

> Download **Pretrained GOPRO_wVAE.pth** from blur-kernel-space-exploring repo (link: [GOPRO_wVAE.pth](https://drive.google.com/file/d/1QMUY8mxUMgEJty2Gk7UY0WYmyyYRY7vS/view) and then move it to diffusion-posterior-sampling/bkse/experiments/pretrained/. 

3. In _diffusion-posterior-sampling/bkse/options/generate_blur/default.yml_ : 
- Change `experiments/pretrained/kernel.pth` into `$HOME/bkse/experiments/pretrained/GOPRO_wVAE.pth` 

4. In _diffusion-posterior-sampling/bkse/options/generic_deblur/default.yml_: 
- Change `experiments/pretrained/kernel.pth` into `$HOME/diffusion-posterior-sampling/bkse/experiments/pretrained/kernel.pth`
- Change `experiments/pretrained/GOPRO_wVAE.pth` into `$HOME/diffusion-posterior-sampling/bkse/experiments/pretrained/GOPRO_wVAE.pth`

Hope this helps!  :~)

**Comment by tomtom1103** [comment]
> Hi @erhathaway, you need to make following changes to work non-linear deblur task work ( I am assuming that you cloned non linear deblur repository as **bkse** name and moved inside diffusion posterior sampling repo) :
> 
> 1. In _diffusion-posterior-sampling/bkse/models/kernel_encoding/kernel_wizard.py_  :
> 
> * Change `import models.arch_util as arch_util` into  `import bkse.models.arch_util as arch_util`
> * Change `from models.backbones.resnet import ResidualBlock_noBN, ResnetBlock` into `from bkse.models.backbones.resnet import ResidualBlock_noBN, ResnetBlock`
> * Change `from models.backbones.unet_parts import UnetSkipConnectionBlock` into `from bkse.models.backbones.unet_parts import UnetSkipConnectionBlock`
> 
> 2. In _diffusion-posterior-sampling/bkse/models/backbones/resnet.py_  :
> 
> * Change `from models.arch_util import initialize_weights` into `from bkse.models.arch_util import initialize_weights`
> 
> > Download **Pretrained GOPRO_wVAE.pth** from blur-kernel-space-exploring repo (link: [GOPRO_wVAE.pth](https://drive.google.com/file/d/1QMUY8mxUMgEJty2Gk7UY0WYmyyYRY7vS/view) and then move it to diffusion-posterior-sampling/bkse/experiments/pretrained/.
> 
> 3. In _diffusion-posterior-sampling/bkse/options/generate_blur/default.yml_ :
> 
> * Change `experiments/pretrained/kernel.pth` into `$HOME/bkse/experiments/pretrained/GOPRO_wVAE.pth`
> 
> 4. In _diffusion-posterior-sampling/bkse/options/generic_deblur/default.yml_:
> 
> * Change `experiments/pretrained/kernel.pth` into `$HOME/diffusion-posterior-sampling/bkse/experiments/pretrained/kernel.pth`
> * Change `experiments/pretrained/GOPRO_wVAE.pth` into `$HOME/diffusion-posterior-sampling/bkse/experiments/pretrained/GOPRO_wVAE.pth`
> 
> Hope this helps! :~)

works perfectly! thank you.

**Comment by hyungjin-chung** [comment]
Thanks @Siddharth-Shrivastava7 for your kind answer! Closing the issue as there are no more activities.
